name: Build and Deploy
on:
  push:
    branches:
      - master
      - development
  schedule:
    - cron: '0 0 * * *' # Every night at midnight
  workflow_dispatch:  # Manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo step
        run: echo "This is an echo step"
