name: Build and Deploy
on:
  workflow_dispatch:  # Manual triggering

jobs:
  setup-pypi-url:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PyPI API packages URL environment variable
        if: github.ref == 'refs/heads/main'
        run: echo "Setting PyPI Package URL for main branch"
        env:
            PYPI_API_PACKAGE_URL: "https://test.ssss.com/repository/pypi-nuxeopublic/simple"
      - name: Setup PyPI API packages URL environment variable
        if: github.ref != 'refs/heads/main'
        run: echo "Setting PyPI Package URL for non-main branch"
        env:
            PYPI_API_PACKAGE_URL: "https://${{ env.PYPI_API_NUXEO_PACKAGE_USERNAME }}:${{ env.PYPI_API_NUXEO_PACKAGE_TOKEN }}@packages.nuxeo.com/repository/pypi-internal/simple"
      - name: Debug and print environment variable
        run: |
          echo "PYPI_API_PACKAGE_URL: $PYPI_API_PACKAGE_URL"
          echo "PYPI_API_PACKAGE_URL from env: ${{ env.PYPI_API_PACKAGE_URL }}"
