name: Build and Deploy
on:
  workflow_dispatch:  # Manual triggering

jobs:
  setup-pypi-url:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PyPI API packages URL environment variable for the 'master' branch
        if: github.ref == 'refs/heads/main'
        run: echo "Setting PyPI Package URL"
        env:
          PYPI_API_PACKAGE_URL: "https://test.ssss.com/repository/pypi-nuxeopublic/simple"

      - name: Setup PyPI API packages URL environment variable for non-'master' branches
        if: github.ref != 'refs/heads/main'
        run: echo "Setting PyPI Package URL"
        env:
          PYPI_API_PACKAGE_URL: "https://${{ env.PYPI_API_NUXEO_PACKAGE_USERNAME }}:${{ env.PYPI_API_NUXEO_PACKAGE_TOKEN }}@packages.nuxeo.com/repository/pypi-internal/simple"
      - name: Debug environment variable
        run: echo "PYPI_API_PACKAGE_URL:$PYPI_API_PACKAGE_URL"

      - name: Print env value
        run: echo "${{ env.PYPI_API_PACKAGE_URL }}"

      - name: Debug environment variable
        run: echo "PYPI_API_PACKAGE_URL:$PYPI_API_PACKAGE_URL"


