name: Build and Deploy sushiltest1
on:
    branches:
        - master
        - development
jobs:
  set-environment:
      runs-on: ubuntu-latest
      steps:
        - name: Set Doc Environment based on branch name
          run: |
              TARGET_BRANCH=${{ github.ref }}
              if [[ "$TARGET_BRANCH" == "master" ]]; then
                echo "Environment: production"
              elif [[ "$TARGET_BRANCH" == "development" ]]; then
                echo "Environment: development"
              else
                echo "Environment: Wrong Environment"
              fi
            echo "environment: ${{ env.NAME }}"
            echo "environment: ${{ env.TEST }}"
      