name: Build and Deploy sushiltest1
on:
  pull_request:
    branches:
        - master
        - development
jobs:
  set-environment:
      runs-on: ubuntu-latest
      steps:
        - name: Set Doc Environment based on branch name
          run: |
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              TARGET_BRANCH=${{ github.head_ref }}
              if [[ "$TARGET_BRANCH" == "master" ]]; then
                echo "Environment: production"
              elif [[ "$TARGET_BRANCH" == "development" ]]; then
                echo "Environment: development"
              else
                echo "Environment: Wrong Environment"
              fi
            fi
            echo "environment: ${{ env.NAME }}"
            echo "environment: ${{ env.TEST }}"
      