name: Set Output Variable Example

on:
  push:
    branches:
      - main
      - development

jobs:
  set-output:
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.test.outputs.my_env }}
    steps:
      - name: Set Doc Environment based on branch name
        id: test
        run: |
          TARGET_BRANCH=${{ github.ref }}
          if [[ "$TARGET_BRANCH" == "refs/heads/main" ]]; then
             echo "Environment: production"
            echo "my_env=production" >> $GITHUB_ENV
            echo "my_env=production" >> $GITHUB_PATH
          elif [[ "$TARGET_BRANCH" == "refs/heads/development" ]]; then
            echo "Environment: development"
            echo "my_env=development" >> $GITHUB_ENV
            echo "my_env=development" >> $GITHUB_PATH
          else
            echo "my_env=Wrong Environment" >> $GITHUB_ENV
          fi

  display-output:
    needs: set-output
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-output.outputs.my_env }}
    steps:
      - name: Display Output Variable
        run: |
          echo "My Environment: ${{ needs.job1.outputs.my_env }}"
      - name: Display Environment Variable
        run: |
          echo "ENV_CONTEXT_VAR: ${{ env.ENV_CONTEXT_VAR }}"
          echo "environment: ${{ env.my_env }}"
