name: Build and Deploy

on:
  push:
    branches:
      - main
      - development

jobs:
  set-environment:
    runs-on: ubuntu-latest  

    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || github.ref == 'refs/heads/development' && 'development' || '' }}

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Nginx Config Test and Restart
        run: |
          ssh -i "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" \
            "${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}" \
            "service nginx configtest && service nginx restart"

      - name: Deploy to Server
        run: |
          rsync -Wxvuk --delete site/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/opt/www/doc/
          rsync redirects.txt ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/etc/nginx/redirects.txt
          rsync redirects_pageid.txt ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/etc/nginx/redirects_pageid.txt
