name: Set Output Variable Example

on:
  push:
    branches:
      - main
      - dev*

jobs:
  set-output:
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.set-output.outputs.my_env }}
    steps:
      - name: Set Doc Environment based on branch name
        run: |
          TARGET_BRANCH=${{ github.ref }}
          if [[ "$TARGET_BRANCH" == "refs/heads/main" ]]; then
            echo "Environment: production"
            echo "::set-output name=my_env::production"
          elif [[ "$TARGET_BRANCH" == "refs/heads/development" ]]; then
            echo "Environment: development"
            echo "::set-output name=my_env::development"
          else
            echo "Environment: Wrong Environment"
          fi

  display-output:
    needs: set-output
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.set-output.outputs.my_env }}
    steps:
      - name: Display Output Variable
        run: |
          echo "My Environment: ${{ needs.set-output.outputs.my_env }}"
      - name: Display Environment Variable
        run: |
          echo "ENV_CONTEXT_VAR: ${{ env.ENV_CONTEXT_VAR }}"
          echo "environment: ${{ env.DOC_ENV }}"
