name: Build and Deploy

on:
  push:
    branches:
      - main
      - development

jobs:
  set-environment:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/development' && 'development' || '' }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Display Environment Variable
        run: |
          echo "Environment: ${{ github.event_name }}"
          echo "ENV_CONTEXT_VAR: ${{ env.ENV_CONTEXT_VAR }}"
          echo "environment: ${{ vars.NAME }}"
