name: Build and Deploy

on:
  push:
    branches:
      - main
      - development

jobs:
  set-environment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Display Environment Variable
        run: |
          echo "Environment: ${{ github.event_name }}"
          echo "ENV_CONTEXT_VAR: ${{ env.ENV_CONTEXT_VAR }}"
          echo "environment: ${{ env.NAME }}"
