name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

    - name: Build Site
      uses: chabad360/hugo-actions@3a5b10adf0b017f695597e22ebcb79e40fd6cb4e #v2
      with:
        buildPath: 'public'
        hugoVersion: 'extended_0.80.0'
        args: -t hyde

    - name: upload artificate
      uses: actions/upload-artifact@v4
      with: 
        name: benchmarks-artifact
        path: ${{ github.workspace }}/public
