name: Build and Deploy Doc.Nuxeo.com
on:
  pull_request:
    branches:
        - master
        - development
jobs:
  set-environment:
      runs-on: ubuntu-latest
      steps:
        - name: Set Doc Environment based on branch name
          run: |
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              TARGET_BRANCH=${{ github.head_ref }}
              if [[ "$TARGET_BRANCH" == "master" ]]; then
                echo "Environment: production"
                echo "::set-env name=DOC_ENV::production"
              elif [[ "$TARGET_BRANCH" == "development" ]]; then
                echo "Environment: development"
                echo "::set-env name=DOC_ENV::development"
              else
                echo "Environment: Wrong Environment"
                echo "::set-env name=DOC_ENV::Wrong Environment"
              fi
            fi
          echo "environment: ${{ vars.NAME }}"
          echo "environment: ${{ vars.TEST }}"
      