name: Build and Deploy
on:
  pull_request:
    branches:
      -  main
      - development

jobs:
  set-environment:
    environment: 
      name: ${{ github.base_ref }} 
    runs-on: ubuntu-latest
    steps:
      
      - name: Display Environment Variable
        run: |
          echo "environment: ${{ vars.NAME }}"
      