name: Set Output Variable Example

on:
  push:
    branches:
      - main
      - dev*

jobs:
  set-output:
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.set-output.outputs.my_env }}
    steps:
      - name: Set Output Variable
        id: set-output
        run: echo "::set-output name=my_env::development"

  display-output:
    needs: set-output
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.set-output.outputs.my_env }}
    steps:
      - name: Display Output Variable
        run: |
          echo "My Environment: ${{ needs.set-output.outputs.my_env }}"
      - name: Display Environment Variable
        run: |
          echo "ENV_CONTEXT_VAR: ${{ vars.ENV_CONTEXT_VAR }}"
          echo "environment: ${{ vars.NAME }}"
