name: Build and Deploy

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set-environment.outputs.env }}
    steps:
      - name: Set Environment based on branch name
        id: set-environment
        run: echo "env=${{ github.base_ref }}" >> $GITHUB_ENV
      - name: Display Environment Variable
        run: |
          echo "${{ steps.set-environment.outputs.env }}"
          echo "env: ${{ vars.NAME }}"

  deploy:
    needs: set-environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-environment.outputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      