name: Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: sushil

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

    - name: Debug Workspace
      run: |
        ls -al $GITHUB_WORKSPACE
        ls -al $RUNNER_WORKSPACE


    - name: upload artificate
      uses: actions/upload-artifact@v4
      with: 
        name: benchmarks-artifact
        path: ${{ github.workspace }}/public
        
     
